### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AnthonyMillerSF** [ladydascalie/currency#2]
Thanks so much for putting these together. Its so convenient! I'd really love to use this, but our company can't use any open-source code without a license. Would you mind adding a permissive license so that we can use this code?

The industry standard for ease of use is the MIT license.

Thanks!

**Comment by ladydascalie** [comment]
@AnthonyMillerSF I feel really bad about taking so long to notice your comment!
I have added an MIT license to the repository, and plan on making some improvements to ensure the data is always fresh.
Stay tuned and I hope you still find some use for this package!
